#!/bin/sh
#!/bin/bash

F61=/DATA/a_modulo-7/session_telegram.txt

# Leer nombres de las sesiones de telegram
telegram1=$(head -1 $F61 | tail -1)


F1=/DATA/a_modulo-7/nro_screen_telegram_s1.txt

# Leer Numero de sesion
NUM=$(head -1 $F1 | tail -1)

#sleep 10
screen -S $NUM.$telegram1 -p 0 -X stuff "`printf "status_online\r"`";


