#!/bin/bash

r=$RANDOM
echo "$r"

F60=/DATA/a_modulo-7/session_sqsh.txt
F61=/DATA/a_modulo-7/session_telegram.txt

# Leer nombres de las sesiones de sqsh
sqsh1=$(head -1 $F60 | tail -1)

# Leer nombres de las sesiones de telegram
telegram1=$(head -1 $F61 | tail -1)


CLIENT=/DATA/a_modulo-3/cliente.txt

# Leer la primera linea del archivo
CLI=$(head -1 $CLIENT | tail -1)

F1=/DATA/a_modulo-7/nro_screen_sqsh.txt

# Leer Numero de sesion
NUM=$(head -1 $F1 | tail -1)

db=/DATA/a_modulo-7/db_rep.txt

# Leer Nombre de la db
DB=$(head -1 $db | tail -1)


screen -S $NUM.$sqsh1 -p 0 -X stuff "`printf "/usr/local/bin/sqsh -S SOMSQL\r"`";

screen -S $NUM.$sqsh1 -p 0 -X stuff "`printf "exec $DB $CLI, $CLI$r\r"`";

screen -S $NUM.$sqsh1 -p 0 -X stuff "`printf "\go\r"`";

sleep 3
screen -S $NUM.$sqsh1 -p 0 -X stuff "`printf "quit\r"`";


USUARIO=/DATA/a_modulo-3/usuario.txt

# Leer la primera linea del archivo
USER=$(head -1 $USUARIO | tail -1)

F2=/DATA/a_modulo-7/nro_screen_telegram.txt

# Leer Numero de sesion
NUM2=$(head -1 $F2 | tail -1)

sleep 1
screen -S $NUM2.$telegram1 -p 0 -X stuff "`printf "send_document $USER /DATA/SHARED/$CLI$r.html\r"`";
