#!/bin/bash

F60=/DATA/a_modulo-7/session_sqsh.txt
F61=/DATA/a_modulo-7/session_telegram.txt

# Leer nombres de las sesiones de sqsh
sqsh1=$(head -1 $F60 | tail -1)

# Leer nombres de las sesiones de telegram
telegram1=$(head -1 $F61 | tail -1)


F1=/DATA/a_modulo-3/formulario-seguro.txt
N1=/DATA/a_modulo-3/numero-seguro.txt
A1=/DATA/a_modulo-3/accion-seguro.txt


F=$(head -1 $F1 | tail -1)

N=$(head -1 $N1 | tail -1)

A=$(head -1 $A1 | tail -1)


CLIENT=/DATA/a_modulo-3/cliente-seguro.txt

# Leer la primera linea del archivo
CLI=$(head -1 $CLIENT | tail -1)

F1=/DATA/a_modulo-7/nro_screen_sqsh.txt

# Leer Numero de sesion
NUM=$(head -1 $F1 | tail -1)


db=/DATA/a_modulo-7/db_aut.txt
db2=/DATA/a_modulo-7/db_aut_test.txt


# Leer Nombre de la db
DB=$(head -1 $db2 | tail -1)

screen -S $NUM.$sqsh1 -p 0 -X stuff "`printf "/usr/local/bin/sqsh -S SOMSQL\r"`";

screen -S $NUM.$sqsh1 -p 0 -X stuff "`printf "exec $DB '$F', $N, '$A'\r"`";

screen -S $NUM.$sqsh1 -p 0 -X stuff "`printf "\go\r"`";

sleep 3
screen -S $NUM.$sqsh1 -p 0 -X stuff "`printf "quit\r"`";
