#!/bin/sh


##mount -t cifs //192.168.1.5/DATA -o username=hgallardo,password=Piedras428 /DATA/SHARED

##sleep 15


# Generacion de sesion principal las opciones -LS graban en el log el contenido de la sesion Telegram
# la opcion -dm crea la sesion en segundo plano desde el arranque
screen -dm telegram-sqsh
screen -LSdm telegram-session


# Generacion de sesiones para procesamiento paralelo S1
screen -dm t-sqsh-s1
screen -LSdm t-session-s1

# Generacion de sesiones para procesamiento paralelo S2
screen -dm t-sqsh-s2
screen -LSdm t-session-s2

echo "1"
sleep 15

F1=/DATA/a_modulo-7/f1.txt 

# Sesion sqsh
F2=/DATA/a_modulo-7/f2.txt 
F3=/DATA/a_modulo-7/f3.txt 
F4=/DATA/a_modulo-7/f4.txt

# Sesion session
F5=/DATA/a_modulo-7/f5.txt
F6=/DATA/a_modulo-7/f6.txt
F7=/DATA/a_modulo-7/f7.txt

# Sesion sqsh-s1
F8=/DATA/a_modulo-7/f8.txt
F9=/DATA/a_modulo-7/f9.txt
F10=/DATA/a_modulo-7/f10.txt

# Sesion session-s1
F11=/DATA/a_modulo-7/f11.txt
F12=/DATA/a_modulo-7/f12.txt
F13=/DATA/a_modulo-7/f13.txt


# Sesion sqsh-s2
F14=/DATA/a_modulo-7/f14.txt
F15=/DATA/a_modulo-7/f15.txt
F16=/DATA/a_modulo-7/f16.txt

# Sesion session-s2
F17=/DATA/a_modulo-7/f17.txt
F18=/DATA/a_modulo-7/f18.txt
F19=/DATA/a_modulo-7/f19.txt


# Sesion principal
F40=/DATA/a_modulo-7/nro_screen_sqsh.txt
F41=/DATA/a_modulo-7/nro_screen_telegram.txt

# Nro de S1 para procesaminento paralelo
F42=/DATA/a_modulo-7/nro_screen_sqsh_s1.txt
F43=/DATA/a_modulo-7/nro_screen_telegram_s1.txt

# Nro de S1 para procesaminento paralelo
F44=/DATA/a_modulo-7/nro_screen_sqsh_s2.txt
F45=/DATA/a_modulo-7/nro_screen_telegram_s2.txt



screen -ls > $F1

echo "2"

#-------------- sqsh ------------------------------------

# Busqueda de todos las lineas con ##
grep -r ".telegram-sqsh" $F1 > $F2

# Elimina la informacion entre ()
sed 's/([^)]*)//g' $F2 > $F3

# Eliminacion de espacios en blanco
sed 's/.telegram-sqsh//' $F3 > $F4

# Eliminacion de los espacios en blanco  adelante y atras
sed 's/^[ \t]*//;s/[ \t]*$//' $F4 > $F40

sleep 5

# Leer Numero de sesion
NUM=$(head -1 $F40 | tail -1)

screen -S $NUM.telegram-sqsh -p 0 -X stuff "`printf "su\r"`";
sleep 1
screen -S $NUM.telegram-sqsh -p 0 -X stuff "`printf "cd /root\r"`";


echo "3"

#-------------- telegram ------------------------------------

# Busqueda de todos las lineas con ##
grep -r ".telegram-session" $F1 > $F5

# Elimina la informacion entre ()
sed 's/([^)]*)//g' $F5 > $F6

# Eliminacion de espacios en blanco
sed 's/.telegram-session//' $F6 > $F7

# Eliminacion de los espacios en blanco  adelante y atras
sed 's/^[ \t]*//;s/[ \t]*$//' $F7 > $F41

echo "4"

sleep 5


# Leer Numero de sesion 
NUM2=$(head -1 $F41 | tail -1)

screen -S $NUM2.telegram-session -p 0 -X stuff "`printf "su\r"`";
sleep 1
screen -S $NUM2.telegram-session -p 0 -X stuff "`printf "cd /DATA/tg\r"`";

sleep 10
screen -S $NUM2.telegram-session -p 0 -X stuff "`printf "./telegram -k tg-server.pub\r"`";

#sleep 5
#screen -S $NUM2.telegram-session -p 0 -X stuff "`printf "status_online\r"`";


echo "5"

#-------------- sqsh-s1 ------------------------------------

# Busqueda de todos las lineas con ##
grep -r ".t-sqsh-s1" $F1 > $F8

# Elimina la informacion entre ()
sed 's/([^)]*)//g' $F8 > $F9

# Eliminacion de espacios en blanco
sed 's/.t-sqsh-s1//' $F9 > $F10

# Eliminacion de los espacios en blanco  adelante y atras
sed 's/^[ \t]*//;s/[ \t]*$//' $F10 > $F42

sleep 5

echo "6"

# Leer Numero de sesion
NUM3=$(head -1 $F42 | tail -1)

screen -S $NUM3.t-sqsh-s1 -p 0 -X stuff "`printf "su\r"`";

sleep 1
screen -S $NUM3.t-sqsh-s1 -p 0 -X stuff "`printf "cd /root\r"`";

echo "7"

#-------------- telegram-s1 ------------------------------------

# Busqueda de todos las lineas con ##
grep -r ".t-session-s1" $F1 > $F11

# Elimina la informacion entre ()
sed 's/([^)]*)//g' $F11 > $F12

# Eliminacion de espacios en blanco
sed 's/.t-session-s1//' $F12 > $F13

# Eliminacion de los espacios en blanco  adelante y atras
sed 's/^[ \t]*//;s/[ \t]*$//' $F13 > $F43


sleep 5

echo "8"

# Leer Numero de sesion 
NUM4=$(head -1 $F43 | tail -1)

screen -S $NUM4.t-session-s1 -p 0 -X stuff "`printf "su\r"`";

sleep 1
screen -S $NUM4.t-session-s1 -p 0 -X stuff "`printf "cd /DATA/tg\r"`";

sleep 10
screen -S $NUM4.t-session-s1 -p 0 -X stuff "`printf "./telegram -k tg-server.pub\r"`";

#sleep 5
#screen -S $NUM4.t-session-s1 -p 0 -X stuff "`printf "status_online\r"`";

echo "9"

#-------------- sqsh-s2 ------------------------------------

# Busqueda de todos las lineas con ##
grep -r ".t-sqsh-s2" $F1 > $F14

# Elimina la informacion entre ()
sed 's/([^)]*)//g' $F14 > $F15

# Eliminacion de espacios en blanco
sed 's/.t-sqsh-s2//' $F15 > $F16

# Eliminacion de los espacios en blanco  adelante y atras
sed 's/^[ \t]*//;s/[ \t]*$//' $F16 > $F44

sleep 5

echo "10"

# Leer Numero de sesion
NUM5=$(head -1 $F44 | tail -1)

screen -S $NUM5.t-sqsh-s2 -p 0 -X stuff "`printf "su\r"`";

sleep 1
screen -S $NUM5.t-sqsh-s2 -p 0 -X stuff "`printf "cd /root\r"`";

echo "11"

#-------------- telegram-s2 ------------------------------------

# Busqueda de todos las lineas con ##
grep -r ".t-session-s2" $F1 > $F17

# Elimina la informacion entre ()
sed 's/([^)]*)//g' $F17 > $F18

# Eliminacion de espacios en blanco
sed 's/.t-session-s2//' $F18 > $F19

# Eliminacion de los espacios en blanco  adelante y atras
sed 's/^[ \t]*//;s/[ \t]*$//' $F19 > $F45


sleep 5

echo "12"

# Leer Numero de sesion 
NUM6=$(head -1 $F45 | tail -1)

screen -S $NUM6.t-session-s2 -p 0 -X stuff "`printf "su\r"`";

sleep 1
screen -S $NUM6.t-session-s2 -p 0 -X stuff "`printf "cd /DATA/tg\r"`";

sleep 10
screen -S $NUM6.t-session-s2 -p 0 -X stuff "`printf "./telegram -k tg-server.pub\r"`";

#sleep 5
#screen -S $NUM6.t-session-s2 -p 0 -X stuff "`printf "status_online\r"`";

echo "13"
