#!/bin/sh


##mount -t cifs //192.168.1.5/DATA -o username=hgallardo,password=Piedras428 /DATA/SHARED

##sleep 15


F60=/DATA/a_modulo-7/session_sqsh.txt
F61=/DATA/a_modulo-7/session_telegram.txt 


# Leer nombres de las sesiones de sqsh
sqsh1=$(head -1 $F60 | tail -1)
sqsh2=$(head -2 $F60 | tail -1)
sqsh3=$(head -3 $F60 | tail -1)

# Leer nombres de las sesiones de telegram
telegram1=$(head -1 $F61 | tail -1)
telegram2=$(head -2 $F61 | tail -1)
telegram3=$(head -3 $F61 | tail -1)




# Generacion de sesion principal las opciones -LS graban en el log el contenido de la sesion Telegram
# la opcion -dm crea la sesion en segundo plano desde el arranque
screen -dm $sqsh1
screen -LSdm $telegram1


# Generacion de sesiones para procesamiento paralelo S1
screen -dm $sqsh2
screen -LSdm $telegram2

# Generacion de sesiones para procesamiento paralelo S2
screen -dm $sqsh3
screen -LSdm $telegram3

echo "1"
sleep 15

F1=/DATA/a_modulo-7/f1.txt 

# Sesion sqsh-s1
F2=/DATA/a_modulo-7/f2.txt 
F3=/DATA/a_modulo-7/f3.txt 
F4=/DATA/a_modulo-7/f4.txt

# Sesion telegram-s1
F5=/DATA/a_modulo-7/f5.txt
F6=/DATA/a_modulo-7/f6.txt
F7=/DATA/a_modulo-7/f7.txt

# Sesion sqsh-s2
F8=/DATA/a_modulo-7/f8.txt
F9=/DATA/a_modulo-7/f9.txt
F10=/DATA/a_modulo-7/f10.txt

# Sesion telegram-s2
F11=/DATA/a_modulo-7/f11.txt
F12=/DATA/a_modulo-7/f12.txt
F13=/DATA/a_modulo-7/f13.txt


# Sesion sqsh-s3
F14=/DATA/a_modulo-7/f14.txt
F15=/DATA/a_modulo-7/f15.txt
F16=/DATA/a_modulo-7/f16.txt

# Sesion telegram-s3
F17=/DATA/a_modulo-7/f17.txt
F18=/DATA/a_modulo-7/f18.txt
F19=/DATA/a_modulo-7/f19.txt


# Sesion principal
F40=/DATA/a_modulo-7/nro_screen_sqsh_s1.txt
F41=/DATA/a_modulo-7/nro_screen_telegram_s1.txt

# Nro de S1 para procesaminento paralelo
F42=/DATA/a_modulo-7/nro_screen_sqsh_s2.txt
F43=/DATA/a_modulo-7/nro_screen_telegram_s2.txt

# Nro de S1 para procesaminento paralelo
F44=/DATA/a_modulo-7/nro_screen_sqsh_s3.txt
F45=/DATA/a_modulo-7/nro_screen_telegram_s3.txt



screen -ls > $F1

#-------------- sqsh-s1 ------------------------------------

# Busqueda de todos las lineas con ##
grep -r ".$sqsh1" $F1 > $F2

# Elimina la informacion entre ()
sed 's/([^)]*)//g' $F2 > $F3

# Eliminacion de espacios en blanco
sed 's/.$sqsh1//' $F3 > $F4

# Eliminacion de los espacios en blanco  adelante y atras
sed 's/^[ \t]*//;s/[ \t]*$//' $F4 > $F40

sleep 5

# Leer Numero de sesion
NUM=$(head -1 $F40 | tail -1)

screen -S $NUM.$sqsh1 -p 0 -X stuff "`printf "su\r"`";
sleep 1
screen -S $NUM.$sqsh1 -p 0 -X stuff "`printf "cd /root\r"`";


#-------------- telegram-s1 ------------------------------------

# Busqueda de todos las lineas con ##
grep -r ".$telegram1" $F1 > $F5

# Elimina la informacion entre ()
sed 's/([^)]*)//g' $F5 > $F6

# Eliminacion de espacios en blanco
sed 's/.$telegram1//' $F6 > $F7

# Eliminacion de los espacios en blanco  adelante y atras
sed 's/^[ \t]*//;s/[ \t]*$//' $F7 > $F41

sleep 5


# Leer Numero de sesion 
NUM2=$(head -1 $F41 | tail -1)

screen -S $NUM2.$telegram1 -p 0 -X stuff "`printf "su\r"`";
sleep 1
screen -S $NUM2.$telegram1 -p 0 -X stuff "`printf "cd /DATA/tg\r"`";

sleep 10
screen -S $NUM2.$telegram1 -p 0 -X stuff "`printf "./telegram -k tg-server.pub\r"`";

#sleep 5
#screen -S $NUM2.$telegram1 -p 0 -X stuff "`printf "status_online\r"`";


#-------------- sqsh-s2 ------------------------------------

# Busqueda de todos las lineas con ##
grep -r ".$sqsh2" $F1 > $F8

# Elimina la informacion entre ()
sed 's/([^)]*)//g' $F8 > $F9

# Eliminacion de espacios en blanco
sed 's/.$sqsh2//' $F9 > $F10

# Eliminacion de los espacios en blanco  adelante y atras
sed 's/^[ \t]*//;s/[ \t]*$//' $F10 > $F42

sleep 5


# Leer Numero de sesion
NUM3=$(head -1 $F42 | tail -1)

screen -S $NUM3.$sqsh2 -p 0 -X stuff "`printf "su\r"`";

sleep 1
screen -S $NUM3.$sqsh2 -p 0 -X stuff "`printf "cd /root\r"`";

#-------------- telegram-s2 ------------------------------------

# Busqueda de todos las lineas con ##
grep -r ".$telegram2" $F1 > $F11

# Elimina la informacion entre ()
sed 's/([^)]*)//g' $F11 > $F12

# Eliminacion de espacios en blanco
sed 's/.$telegram2//' $F12 > $F13

# Eliminacion de los espacios en blanco  adelante y atras
sed 's/^[ \t]*//;s/[ \t]*$//' $F13 > $F43


sleep 5

# Leer Numero de sesion 
NUM4=$(head -1 $F43 | tail -1)

screen -S $NUM4.$telegram2 -p 0 -X stuff "`printf "su\r"`";

sleep 1
screen -S $NUM4.$telegram2 -p 0 -X stuff "`printf "cd /DATA/tg\r"`";

sleep 10
screen -S $NUM4.$telegram2 -p 0 -X stuff "`printf "./telegram -k tg-server.pub\r"`";

#sleep 5
#screen -S $NUM4.$telegram2 -p 0 -X stuff "`printf "status_online\r"`";


#-------------- sqsh-s3 ------------------------------------

# Busqueda de todos las lineas con ##
grep -r ".$sqsh3" $F1 > $F14

# Elimina la informacion entre ()
sed 's/([^)]*)//g' $F14 > $F15

# Eliminacion de espacios en blanco
sed 's/.$sqsh3//' $F15 > $F16

# Eliminacion de los espacios en blanco  adelante y atras
sed 's/^[ \t]*//;s/[ \t]*$//' $F16 > $F44

sleep 5


# Leer Numero de sesion
NUM5=$(head -1 $F44 | tail -1)

screen -S $NUM5.$sqsh3 -p 0 -X stuff "`printf "su\r"`";

sleep 1
screen -S $NUM5.$sqsh3 -p 0 -X stuff "`printf "cd /root\r"`";


#-------------- telegram-s3 ------------------------------------

# Busqueda de todos las lineas con ##
grep -r ".$telegram3" $F1 > $F17

# Elimina la informacion entre ()
sed 's/([^)]*)//g' $F17 > $F18

# Eliminacion de espacios en blanco
sed 's/.$telegram3//' $F18 > $F19

# Eliminacion de los espacios en blanco  adelante y atras
sed 's/^[ \t]*//;s/[ \t]*$//' $F19 > $F45


sleep 5

# Leer Numero de sesion 
NUM6=$(head -1 $F45 | tail -1)

screen -S $NUM6.$telegram3 -p 0 -X stuff "`printf "su\r"`";

sleep 1
screen -S $NUM6.$telegram3 -p 0 -X stuff "`printf "cd /DATA/tg\r"`";

sleep 10
screen -S $NUM6.$telegram3 -p 0 -X stuff "`printf "./telegram -k tg-server.pub\r"`";

#sleep 5
#screen -S $NUM6.$telegram3 -p 0 -X stuff "`printf "status_online\r"`";
