#!/bin/bash

F61=/DATA/a_modulo-7/session_telegram.txt

# Leer nombres de las sesiones de telegram
telegram3=$(head -3 $F61 | tail -1)

F1=/DATA/a_modulo-7/nro_screen_telegram_3.txt

# Leer Numero de sesion
NUM=$(head -1 $F1 | tail -1)

screen -S $NUM.$telegram3 -p 0 -X stuff "`printf "./telegram -k tg-server.pub\r"`";

sleep 3

USUARIO=/DATA/s_2/a_modulo-3/usuario.txt

# Leer la primera linea del archivo
USER=$(head -1 $USUARIO | tail -1)


screen -S $NUM.$telegram3 -p 0 -X stuff "`printf "msg $USER Error de procesaminto por favor vuelva a enviar la consulta\r"`";
