#!/bin/bash

F61=/DATA/a_modulo-7/session_telegram.txt 

# Leer nombres de las sesiones de telegram
telegram3=$(head -3 $F61 | tail -1)

F1=/DATA/s_3/a_modulo-3/usuario.txt
F2=/DATA/s_3/a_modulo-3/usuario-s.txt


# Leer la primera linea del archivo
USER=$(head -1 $F1 | tail -1)

# Leer la primera linea del archivo
USER2=$(head -1 $F2 | tail -1)

F3=/DATA/a_modulo-7/nro_screen_telegram_s3.txt

# Leer Numero de sesion
NUM=$(head -1 $F3 | tail -1)

screen -S $NUM.$telegram3 -p 0 -X stuff "`printf "create_secret_chat $USER\r"`";

sleep 3
screen -S $NUM.$telegram3 -p 0 -X stuff "`printf "msg $USER2 Conexion segura establecida\r"`";

